/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_schwarzrot_system_ErrorReader */

#ifndef _Included_de_schwarzrot_system_ErrorReader
#define _Included_de_schwarzrot_system_ErrorReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_schwarzrot_system_ErrorReader
 * Method:    fetchMessage
 * Signature: ()Lde/schwarzrot/system/SystemMessage;
 */
JNIEXPORT jobject JNICALL Java_de_schwarzrot_system_ErrorReader_fetchMessage
  (JNIEnv *, jobject);

/*
 * Class:     de_schwarzrot_system_ErrorReader
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_schwarzrot_system_ErrorReader_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
